spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_learning
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  thymeleaf:
    cache: false